### ISSUE TITLE
[backend] group_service change create, delete endpoint 

### ISSUE THREAD

**Issue by zeroFruit** [swsnu/swpp2019-team16#118]
### Subject of this issue

Currently, the endpoint for creating, deleting group is `POST ~~/create`, `POST ~~/delete`. This should be changed into `POST ~~/`, `DELETE ~~/`

![image](https://user-images.githubusercontent.com/18715362/69160612-3d69d000-0b2d-11ea-872d-68f13fd28faf.png)

**Comment by dkim94** [comment]
creating group : POST
updating group: PATCH
