### ISSUE TITLE
[Alpha Testing]google api load issue

### ISSUE THREAD

**Issue by sungbin92** [swsnu/swpp2019-team16#168]
계속 로드하는동안 오류가 난다는 메세지가 뜹니다.

**Comment by sungbin92** [comment]
옵션을 선택하면 자동으로 다음 옵션이 뜨게끔 해주시면 더 좋을 것 같습니다.

**Comment by zeroFruit** [comment]
We refine your issue into #186, #188. So I'll close this issue. Thx for comment.
