### ISSUE TITLE
[Alpha testing] Sign up error

### ISSUE THREAD

**Issue by csh3695** [swsnu/swpp2019-team16#169]
가입이 안됩니다.
update : 가입후 리다이렉팅이 필요할 것 같습니다.

**Comment by dkim94** [comment]
브라우저 새로 띄워서 해보시겠어요? 시크릿창이라든지

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #190, #191! So I'll close 👍
