### ISSUE TITLE
[alpha testing] undefined URL issue

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team16#170]
### Subject of this issue

`http://52.141.28.35/ㄱㄷ볃ㄴㅅ` does not link to any, which is possible security issue.

### To reproduce

redirect to `http://52.141.28.35/ㄱㄷ볃ㄴㅅ`.

### Detail Description

`404 Undefined` or something similar (there is no such thing) should be implemented
examples: [apple](https://www.apple.com/asdfasdf), [github](https://github.com/aasdfqwefqwefdf)

Remember to use helpful labels and milestones.

**Comment by zeroFruit** [comment]
Thanks for the feedback!

**Comment by zeroFruit** [comment]
We refine your issue into #187! So I'll close 👍
