### ISSUE TITLE
[Alpha Testing] Sign up error

### ISSUE THREAD

**Issue by kooyunmo** [swsnu/swpp2019-team16#172]
안녕하세요. 회원가입시에 다음과 같은 시나리오에서 버그가 있는 걸로 보입니다

1. rider / driver를 제외한 다른 항목들은 채운 상태에서 submit을 누름
2. rider / driver를 선택하지 않았으니 로그인이 당연히 안됨. (이 때 피드백 메세지가 있으면 좋을 듯 합니다)
3. rider / driver를 선택한 순간 submit을 누르지 않았는데 바로 로그인이 됨

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #190, #191! So I'll close 👍
