### ISSUE TITLE
[Alpha Test] SignUp / SignIn bug

### ISSUE THREAD

**Issue by sanggggg** [swsnu/swpp2019-team16#178]
- SignUp 성공시 redirect되는 페이지가 없어 성공 여부를 확인할 수 가 없어 보입니다.
- Home 버튼 클릭시 uri가 `/` 가 아닌 `/intro' 로 연결되는데 이 페이지가 구현이 안되 있는 것 같습니다.-
- 팀원 4명이서 녹두 -> 긱삼으로 가는 4인 택시요청을 같이 보냈음에 불구하고 로딩창만 뜨고 실제 카풀 매칭이 성사되지 않습니다

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #190, #191! So I'll close 👍
