### ISSUE TITLE
[Alpha Testing] main page UI

### ISSUE THREAD

**Issue by coffeetea99** [swsnu/swpp2019-team16#181]
처음 Where are you? 페이지에서 어떻게 진행해야 하는지 몰라 해멨습니다. 아래로 스크롤해 달라는 메시지를 적으면 좋을 것 같습니다.
또한 지도를 화면 아래쪽이 아니라 왼쪽이나 오른쪽에 넣으면 지도의 가로세로 비율이 적당해질 것 같습니다.

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #186! So I'll close 👍
