### ISSUE TITLE
[Alpha Testing] About UI 

### ISSUE THREAD

**Issue by kooyunmo** [swsnu/swpp2019-team16#182]
버그는 아니지만 전반적인 UI와 관련하여 이런 점이 개선되면 좋겠다 싶어서 이슈 남깁니다!

로그인 후에 카풀 매칭 정보를 입력할 때 선택후 아래로 스크롤을 내려야 다음 정보를 입력할 수 있는데 아래로 스크롤을 내려야 다음 입력창이 있다는 걸 알아차리는데 시간이 좀 걸렸습니다.

1. 자동으로 스크롤이 내려가거나
2. 아래를 가리키는 화살표 아이콘을 삽입

하면 UI 면에서 더 좋을 듯 합니다.

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #186! So I'll close 👍
