### ISSUE TITLE
[Alpha Testing] Can't load google maps correctly

### ISSUE THREAD

**Issue by taehioum** [swsnu/swpp2019-team16#183]
'''
util.js:233 Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys'''

this error message is shown, with a pop up that goes like "Google 지도를 제대로 로드할 수 없습니다"

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #188! So I'll close 👍
