### ISSUE TITLE
[alpha testing] issue while registering

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team16#184]
<img width="1440" alt="스크린샷 2019-12-05 오후 6 56 45" src="https://user-images.githubusercontent.com/17784659/70224693-11875500-1791-11ea-8ed3-2babcf7380c5.png">

### Subject of this issue

정상적으로 등록했음에도 `Email or password is wrong` 이라는 팝업이 등장합니다.

### To reproduce

go to register page,
enter:
Email : lightb0x@naver.com
password: asdfasdf
password confirmation: asdfasdf
Car type: C-130
Plat No.: 1234

### Detail Description

정상적으로 등록되었다는 팝업 후 에러 팝업이 등장합니다.

Remember to use helpful labels and milestones.

**Comment by zeroFruit** [comment]
Thanks for the feedback :) We refine your issue into #190, #191! So I'll close 👍
