### ISSUE TITLE
[alpha testing] redirect to some place right after registering

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team16#185]
<img width="1440" alt="스크린샷 2019-12-05 오후 7 00 15" src="https://user-images.githubusercontent.com/17784659/70225056-a25e3080-1791-11ea-9c12-dbb753032858.png">

### Subject of this issue

등록 후 바로 로그인되며 `http://52.141.28.35/requestcall`로 이동되고 어떠한 버튼등이 표시되지 않습니다.

### To reproduce

driver 로 등록하면 바로 이쪽으로 넘어가게 됩니다.

### Detail Description

Remember to use helpful labels and milestones.

**Comment by zeroFruit** [comment]
We refine your issue on #193 Thanks for comment!
