### ISSUE TITLE
[frontend] Add common Header component

### ISSUE THREAD

**Issue by zeroFruit** [swsnu/swpp2019-team16#34]
### Subject of this issue

Add Header component

### Detail Description

This is common component of our service. Header component should have following properties.

* `onClickMenu`: function - event handler when click menu on right top side
* `onClickLogo`: function - event handler when click logo on left top side
* `onClickLogout`: function - event handler when click 'Logout' button
* `onClickChargePoint`: function - event handler when click 'Charge Point' menu button

#### Reference

https://material-ui.com/components/app-bar/

**Comment by dkim94** [comment]
Can you explain how header is different to heading?
Is header the main logo, and heading the title of the page? Have I understood it correctly?

**Comment by zeroFruit** [comment]
What I think what 'Header' is [this](https://material-ui.com/components/app-bar/)!

The heading is the title of the section

**Comment by dkim94** [comment]
Thanks ;)
