### ISSUE TITLE
[frontend] Add Group module (action, reducer, saga)

### ISSUE THREAD

**Issue by zeroFruit** [swsnu/swpp2019-team16#35]
### Subject of this issue

Need to add Group module action, reducer, redux-saga

### Detail Description

Group module should have following actions

* `ACCEPT_GROUP`: On the driver side, the driver can accept group with this action
* `ON_TAXI`: On the rider side, the rider can notify that his/her self get on the taxi
* `DEPARTURE`: On the driver side, the driver can departure his/her own vehicle through this action
* `FETCH_MY_GROUP`: On driver/rider side, the driver/rider can fetch my group info

**Comment by dkim94** [comment]
Add action: NOTIFY_DRIVER_LOCATION

**Comment by dkim94** [comment]
Add action: CONFIRM_COST: On driver side, the driver can input the final cost.

**Comment by dkim94** [comment]
Add action: NOTIFY_DRIVER_LOCATION : On driver side, the driver sends location info to server.
